# PostgreSQL Container
# Using the MapR Volume Driver Plugin for dynamic provisioning

# Service
---
apiVersion: v1
kind: Service
metadata:
  name: mapr-k8-postgres
  namespace: mapr-apps
spec:
  type: NodePort
  selector:
    app: mapr-k8-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30003
