# MapR Volume Driver Plugin for Kubernetes

# MapR Apps Namespace
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: mapr-apps
#   labels:
#     name: mapr-apps


# Secret to authenticate with MapR Converged Data Platform
---
apiVersion: v1
kind: Secret
metadata:
  name: mapr-provisioner-secrets
  namespace: mapr-apps
type: Opaque
data:
# base64 encoding: "echo -n '<username/password>' | base64" eg:
# echo -n 'mapr' | base64
  MAPR_CLUSTER_USER: "bWFwcg=="
  MAPR_CLUSTER_PASSWORD: "bWFwcg=="

# Ticket to authenticate with MapR Converged Data Platform
---
apiVersion: v1
kind: Secret
metadata:
  name: mapr-ticket-secret
  namespace: mapr-apps
type: Opaque
data:
# To create a Ticket:
# 1. maprlogin password -user mapr
# 2. cat /tmp/maprticket_#### | base64
# 3. combine 6 lines base64 output in single CONTAINER_SECRET line:
  CONTAINER_SECRET: ZGVtby5tYXByLmNvbSBjclcxZWVvMjV1d1p1UFY1NWJYWlBGSHl0T0NxK0tFdVY1V1lFMElmZGlyS3NYT2xYQVRYVGg2TnlGbDgyR0lqbmZVYkhyWnVOb1ZGQWRVS2pQVy9NQUZQaEk1UWhQTVJBWjAvc1hVYWMvTnVIQ1VrZkRmbUVpalpoL3pPVjMzUWNHNXdTQXdDK3Y2YkIwakR6RHNrVk1TSjFoZDJoYzA2WXhPWllyZkxTWnZyUnA1SjU5N1dXNDFQZDdmNlZYL1pDeW9aNnJXS3ExVmdrTmRrQ1Y2aGRUWHFYZEFEcEF1dEZaY2hiazJINy9yenladmVCOE5kYWt4T1h4eWJjb3pMeU5iVUc4MGc2UmdjdmpYZm8vN1IvVEFNYmxqR1R3az0K

# StorageClass for MapR Converged Data Platform
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: maprfs-sc-postgres
   namespace: mapr-apps
provisioner: mapr.com/maprfs
parameters:
    # Configure below MapR cluster details to reflect your MapR cluster configuration
    restServers: "172.16.1.188:8443"
    cldbHosts: "172.16.1.188"
    cluster: "demo.mapr.com"
    securityType: "secure"
    ticketSecretName: "mapr-ticket-secret"
    ticketSecretNamespace: "mapr-apps"
    maprSecretName: "mapr-provisioner-secrets"
    maprSecretNamespace: "mapr-apps"
    namePrefix: "postgres"
    mountPrefix: "/postgres"
    reclaimPolicy: “Retain”
    advisoryquota: "100M"
    auditenabled: "1"
    forceauditenable: "1"
    replication: "3"
    minreplication: "2"
    nsreplication: "3"
    nsminreplication: "2"
    type: "rw"
    mount: "1"


# PersistentVolumeClaim for MapR Converged Data Platform
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: maprfs-pvc-postgres
  namespace: mapr-apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: maprfs-sc-postgres
  resources:
    requests:
      storage: 300M
