# PostgreSQL Container

# Using the MapR Volume Driver Plugin for dynamic provisioning

# Service
---
apiVersion: v1
kind: Service
metadata:
  name: mapr-k8-postgres
  namespace: mapr-apps
spec:
  type: NodePort
  selector:
    app: mapr-k8-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30003


# Pod
---
apiVersion: v1
kind: Pod
metadata:
  name: mapr-k8-postgres
  namespace: mapr-apps
  labels:
    app: mapr-k8-postgres
spec:
  containers:
    - name: mapr-k8-postgres
      imagePullPolicy: Always
      image: mkieboom/mapr-k8-postgres
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
      command:
      - /bin/bash
      - -c
      - "/launch.sh"
      env:
        - name: PGDATA_LOCATION
          value: "/postgres"
        - name: PG_DB
          value: "mapr"
        - name: PG_GROUP
          value: "mapr"
        - name: PG_USER
          value: "mapr"
        - name: PG_PWD
          value: "mapr"
        - name: PG_GID
          value: "5000"
        - name: PG_UID
          value: "5000"
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: maprfs-pvc
          mountPath: "/postgres"
  volumes:
    - name: maprfs-pvc
      persistentVolumeClaim:
        claimName: maprfs-pvc-postgres



